controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


# exemple ancienne route
# page_contact:
#     route: /contact
#     controller: App\Controller\PagesController::contact

# page_cgu:
#     route: /cgu
#     controller: App\Controller\PagesController::cgu